prometheus:
    image: prom/prometheus
    user: root
#    net: "host"
    extra_hosts:
        - "dockerhost:172.17.0.1"
    ports:
        - "127.0.0.1:9090:9090"
    volumes:
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./data:/data/prometheus
    command:
        - --config.file=/etc/prometheus/prometheus.yml
    restart: always

nodeexporter:
    image: prom/node-exporter
    user: root
    volumes: 
        - /proc:/host/proc
        - /sys:/host/sys
        - /:/rootfs
    extra_hosts:
        - "dockerhost:172.17.0.1"
    ports:
        - "172.17.0.1:9091:9100"
    command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always

nginx-prometheus-exporter:
    image: sophos/nginx-vts-exporter
    extra_hosts:
        - "dockerhost:172.17.0.1"
    ports:
        - "172.17.0.1:9092:9913"
    environment:  
        - NGINX_STATUS=http://172.17.0.1:8080/status
    restart: always

mysql-prometheus-exporter:
    image: prom/mysqld-exporter
    extra_hosts:
        - "dockerhost:172.17.0.1"
    ports:
        - "172.17.0.1:9093:9104"
    environment:
        - DATA_SOURCE_NAME=username:password@(172.17.0.1:3306)/
    restart: always

